<a href="https://colab.research.google.com/github/ananthavarshinireddy123-ai/Varshini-Reddy/blob/main/AnomalyDetection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Anomaly Detection in Machine Learning

Definition:
Anomaly detection is the process of finding data points, events, or observations that are significantly different from the rest of the data. These unusual observations are called anomalies or outliers.

How Anomaly Detection Works:

Collect data from the system or application.
Learn the normal pattern of the data.
Compare new data with the learned pattern.
Flag unusual data as anomalies if they differ significantly.

#Types of Anomalies
1.Point Anomaly
A single data point is abnormal.
Example: A bank customer usually spends ₹2,000–₹5,000, but one day spends ₹2,00,000.

2.Contextual Anomaly
A value is abnormal only in a specific context.
Example: A temperature of 5°C is normal in winter but unusual in summer.

3.Collective Anomaly
A group of data points is abnormal together, even if individual points appear normal.
Example: Several small bank transactions made within a few minutes from different locations.

**Applications**
Banking: Detect fraudulent transactions.
Cybersecurity: Identify unauthorized network activity.
Healthcare: Detect abnormal heart rate or blood pressure.
Manufacturing: Find defective products or equipment failures.
Retail: Detect unusual customer purchasing behavior.

**Common Algorithms**
1.Isolation Forest	Isolates unusual observations quickly using random splits.

2.One-Class SVM	Learns the boundary of normal data and detects anything outside it.

3.Local Outlier Factor (LOF)	Detects points that have much lower local density than their neighbors.

4.Autoencoder	A neural network that reconstructs normal data; high reconstruction error suggests an anomaly.

5.DBSCAN	Treats points outside dense clusters as anomalies.

Example

Suppose an ATM records the following withdrawals:

₹500
₹800,
₹1,000,
₹700,
₹900,
₹50,000.

The withdrawal of ₹50,000 is much larger than the others. An anomaly detection system would likely flag this transaction so the bank can verify whether it is legitimate.


#Advantages
Detects fraud and security threats early.
Improves system reliability.
Reduces financial losses.
Supports predictive maintenance by identifying equipment issues before failure.

#Limitations
May incorrectly flag normal events as anomalies (false positives).
Performance depends on data quality.
Rare normal events can sometimes be mistaken for anomalies.

Isolation Forest

In [1]:
from sklearn.ensemble import IsolationForest
import numpy as np

# Sample data
X = np.array([[10], [12], [11], [13], [12], [100]])

# Create and train model
model = IsolationForest(contamination=0.1, random_state=42)
model.fit(X)

# Predict anomalies
predictions = model.predict(X)

print(predictions)

[ 1  1  1  1  1 -1]


One-class SVM

In [ ]:
from sklearn.svm import OneClassSVM
import numpy as np

X = np.array([[10], [12], [11], [13], [12], [100]])

model = OneClassSVM(gamma='auto', nu=0.2)
model.fit(X)

predictions = model.predict(X)

print(predictions)

Local Outlier Factor

In [5]:
from sklearn.neighbors import LocalOutlierFactor
import numpy as np

X = np.array([[10], [12], [11], [13], [12], [100]])

model = LocalOutlierFactor(n_neighbors=2)

predictions = model.fit_predict(X)

print(predictions)

[ 1  1  1  1  1 -1]


DBSCAN

In [4]:
from sklearn.cluster import DBSCAN
import numpy as np

X = np.array([[10], [12], [11], [13], [12], [100]])

model = DBSCAN(eps=5, min_samples=2)

labels = model.fit_predict(X)

print(labels)

[ 0  0  0  0  0 -1]


Autoencoder (TensorFlow/Keras)

In [3]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# Training data (normal data)
X = np.array([[10], [12], [11], [13], [12]], dtype=float)

model = Sequential([
    Dense(4, activation='relu', input_shape=(1,)),
    Dense(2, activation='relu'),
    Dense(4, activation='relu'),
    Dense(1)
])

model.compile(optimizer='adam', loss='mse')
model.fit(X, X, epochs=100, verbose=0)

# Test data
test = np.array([[10], [12], [100]], dtype=float)

reconstructed = model.predict(test)

error = np.mean((test - reconstructed) ** 2, axis=1)

print("Reconstruction Error:", error)

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step
Reconstruction Error: [  101.60066812   148.19426409 10934.37634063]
